; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitm-1]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
build.flash_type=qio
board_build.arduino.memory_type = dio_opi
build_flags =
              -D CORE_DEBUG_LEVEL=5
              -D BOARD_HAS_PSRAM
              -mfix-esp32-psram-cache-issue
              -D ARDUINO_USB_MODE=1
              -D ARDUINO_USB_CDC_ON_BOOT=1
; hook the build process for Firmion
extra_scripts = post:firmion_builder.py