[package]
name = "process"
version = "0.1.0"
authors = ["Steve King <sk@metrokings.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
path = "process.rs"

[dependencies]
log = "0.4.11"
anyhow = "1.0.34"
clap = "2.33.3"

# local dependencies
ast = { path = "../ast" }
diags = { path = "../diags" }
lineardb = { path = "../lineardb" }
irdb = { path = "../irdb" }
engine = { path = "../engine" }
ir_base = { path = "../ir_base" }
